#!/usr/bin/env python3
"""Extract the EXACT tree-mark paths from public/pg-logo.svg and emit a React
component. The logo SVG holds two path groups inside <g id="Layer_1-2">: the
first group is the tree emblem, the second is the "PRIME GOLD" wordmark. We take
the first group's <path d="..."> values verbatim so the hero background is the
real logo mark, not a generic tree."""

import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
svg = (ROOT / "public" / "pg-logo.svg").read_text(encoding="utf-8")

# Everything after the drawing layer starts; the tree group is the first <g> to
# close, so the substring up to the first </g> contains exactly the tree paths.
body = svg.split('id="Layer_1-2"', 1)[1]
tree_region = body.split("</g>", 1)[0]
ds = re.findall(r'\bd="([^"]+)"', tree_region)
assert ds, "no tree paths found"

paths = "\n".join(f'      <path d="{d}" />' for d in ds)
component = f'''import {{ cn }} from "@/lib/cn";

/**
 * Prime Gold logo tree mark — the EXACT emblem paths lifted verbatim from
 * public/pg-logo.svg (first path group). Generated by scripts/gen_tree_component.py.
 * Rendered single-fill (currentColor) so it scales up as atmospheric background
 * texture while remaining pixel-faithful to the logo mark. Decorative only.
 */
export function LogoTreeMark({{ className }}: {{ className?: string }}) {{
  return (
    <svg
      viewBox="0 0 38 37.93"
      fill="currentColor"
      aria-hidden="true"
      className={{cn(className)}}
    >
{paths}
    </svg>
  );
}}
'''
out = ROOT / "components" / "brand" / "LogoTreeMark.tsx"
out.write_text(component, encoding="utf-8")
print(f"wrote {out} with {len(ds)} paths")
